config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :users 
  resources :posts
  resources :clients
  resources :users do 
    resources :clients
  end

  get 'welcome/index'

  root 'welcome#index'

  get 'welcome/bestpractices', to: 'welcome#bestpractices'
  post 'post/post_period_search', to: 'posts#post_period_search', as: 'post_period_search'

end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime
#  updated_at             :datetime
#

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :lockable
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Client < ActiveRecord::Base
	has_many :posts
	belongs_to :user

	def self.find_clients_for_current_user(current_user) #pass in current_user
    clients = Client.where(user_id:current_user.id) #find all clients connected to this current_user
    
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  title           :text
#  submission_date :date
#  created_at      :datetime
#  updated_at      :datetime
#  period          :string
#  client_id       :integer
#  user_id         :integer
#

class Post < ActiveRecord::Base
	belongs_to :client
	belongs_to :user
	validates_presence_of :title, :client_id, :submission_date, :period


  def self.search(search)
    if search
      self.where("period LIKE ?", "%#{search}%")
    else
      self.all
    end
  end 

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  admin                  :boolean
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :clients
  has_many :posts	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController 
  def index
  	@clients = Client.all
  end

  def show
  	@client = get_client
  end

  def new
  	@client = Client.new
  end

  def edit
  	@client = get_client
  end

def create
  	@client = Client.new(client_params)
    @client.user_id = current_user.id 
  	if @client.save
  		redirect_to client_path(@client)
  	else
  		render :new
  	end
  end

  def update
    @client = get_client
    if @client.update(client_params)
      redirect_to clients_path(@client)
  else 
    render :edit
  end
  end

  def destroy
  @client = get_client
  @client.destroy
  redirect_to clients_path
  end

private

	def client_params
		params.require(:client).permit(:name,:user_id)
	end

	def get_client
		@client = Client.find(params[:id])
	end
end






  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)
    @post.user = current_user
  	if @post.save
  		redirect_to post_path(@post)
  	else
  		render :new
  	end
  end

def index
  	if current_user 
      if current_user.admin == true
        @posts = Post.order(params[:sort])
        @post = Post.new
      else
      @posts = current_user.posts
      @post = Post.new
    end
    else
      @posts = Post.all #this should never happen because users should be authenticated 
    end
  end

  def show
  	@post = get_post
  end

  def edit
  	@post = get_post
  end

  def update
    @post = get_post
    if @post.update(post_params)
      redirect_to posts_path(@post)
    else 
    render :edit
    end
  end

  def destroy
    @post = get_post
    @post.destroy
    redirect_to posts_path
  end

  def post_period_search
    @period = params["post"]["period"]
    result = Post.search(@period)
    if current_user.admin != true
      @posts = result.where(user_id: current_user.id) 
    else
      @posts = result
    end
    render :show_posts
  end

private

	def post_params
		params.require(:post).permit(:client_id, :client, :title, :submission_date, :user_id, :period, :user)
	end

	def get_post
		@post = Post.find(params[:id])
	end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def bestpractices
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_periods
		[
			['Dec-2014', 'Dec-2014'],
			['Jan-2015', 'Jan-2015'],
			['Feb-2015', 'Feb-2015'],
			['Mar-2015', 'Mar-2015']
		]
	end	

  def just_your_clients(current_user)
    clients = Client.find_clients_for_current_user(current_user) 
    clients.map do |client| #look up map function 
      [client.name , client.id.to_i] #returns an array with just attributes you want
    end 
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<div class="jumbotron">
<div class="col-md-6">

	<div class="well">
	<%= simple_form_for(@client, html: {:class => 'form-horizontal'} ) do |f| %>

	<p><%= f.input :name, input_html: {:class => 'form-control', placeholder: 'Client Name'} %></p>

	<div style="text-align:center;">
	<p><%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-danger' %></p>
	</div>

	<% end %>
</div>
</div>

app/views/clients/edit.html.erb
<div class="col-md-12">

<h1> Edit Client </h1>

<%= render 'form' %>

</div>
</div>

app/views/clients/index.html.erb
<div class='col-md-12'>
<div class="col-md-8 col-md-offset-2">
<div class="jumbotron">
<h1 style="color:#666666;">Client Index Page</h1>

<div class="table-responsive">

<table class="table table-striped table-hover">

	<tr class="small">
		<th> Client Name </th>
		<th> Posts List </th>
		<th> Edit </th>
		<th> Delete </th>
	</tr>

<% current_user.clients.each do |client| %>

<!-- Code in the loop below MUST match the word within the two long lines after 'do' above -->

	<tr class="small">
		<td> <%= client.name %> </td>
		<td>
			<%= link_to "#{client.name} Posts List", client_path(client), :class => 'btn btn-xs btn-danger'  %> 
		</td>
		<td>
			<%= link_to 'Edit', edit_client_path(client), :class => 'btn btn-xs btn-success'  %>
		</td>
		<td>
			<%= link_to 'Delete', client, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-xs btn-warning' %>
		</td>
			
		</td>	
	</tr>
<% end %>
<%= link_to "Create New Client", new_client_path, :class => 'btn btn-xs btn-success' %>
</table>

</div>
</div>

</div>

app/views/clients/new.html.erb
<div class="col-md-12">

<%= render 'form' %>

</div>
</div>

app/views/clients/show.html.erb
<div class="col-md-12">

<div class="col-md-8">
<div class="jumbotron">
<h1><%=@client.name %></h1>

<p><% @client.posts.each do |post| %>
<ul><li><%= post.title %> | <%= post.submission_date %></li></ul>
	</p>
<% end %>
</div>
</div>

app/views/layouts/_main_nav.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><%= link_to "Index", root_path %></li>
  <% if current_user && current_user.admin != true %>
  	<li role="presentation"><%= link_to "Clients", user_clients_path(current_user.id) %></li>
  	<li role="presentation"><%= link_to "Posts", posts_path %></li>
  <% end %>
  <li role="presentation"><%= link_to "Current Best Practices", welcome_bestpractices_path %></li>


  <% if current_user %>
    <li role="presentation"><%= link_to "Log-out", destroy_user_session_path, :method => :delete %></li>
    <% if current_user.admin == true %>
      <li role="presentation"><%= link_to "Admin", posts_path %></li>
    <% end %>
  <% else %>
  <li role="presentation"><%= link_to "Sign-up", new_user_registration_path %></li>
   <li role="presentation"><%= link_to "Login", user_session_path %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WriterApp</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">

<!-- Add main_nav partial using render -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= render 'layouts/main_nav' %>
<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
	<div class="jumbotron">
	<%= simple_form_for(@post, html: {:class => 'form-horizontal'} ) do |f| %>

  <% if current_user && current_user.admin != true %>
	<p><%= f.association :client, collection: just_your_clients(current_user), label: false , prompt: 'Select Client', input_html: {:class => 'form-control'} %></p>
  <% else %>
  <p><%= f.association :client, label: false , prompt: 'Select Client', input_html: {:class => 'form-control'} %></p>
  <% end %>
	<p><%= f.input :title, label: false, input_html: {:class => 'form-control', placeholder: 'Blog Post Title'} %></p>

	<p><%= f.input :submission_date, label: false, input_html: {:class => 'form-control', placeholder: 'Submission Date'} %> </p>

	<p><%= f.input :period, collection: post_periods, prompt: 'Select Month', label:false, input_html: {:class => 'form-control'}  %></p>

	<div style="text-align:center;">
	<p><%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-danger' %></p>
	</div>

	<% end %>
</div>
</div>

app/views/posts/_searchform.html.erb
<div class="col-md-6">
  

  <div class="well">
  <%= simple_form_for(@post, :url=> post_period_search_path, html: {:class => 'form-horizontal'} ) do |f| %>

  <p><%= f.input :period, collection: post_periods, prompt: 'Select Month', label:false, input_html: {:class => 'form-control'}  %></p>

  <div style="text-align:center;">
  <p><%= f.submit "Submit".html_safe, :class => 'btn btn-lg btn-danger' %></p>
  </div>

  <% end %>
</div>
</div>

app/views/posts/edit.html.erb
<div class="col-md-12">
<h1 style="color:#cc3333;">Edit Post</h1>

<%= render 'form' %>

</div>
</div>

app/views/posts/index.html.erb
<div class='col-md-12'>
<div class="col-md-8 col-md-offset-2">
<div class="jumbotron">
<h1 style="color:#666666;">Posts Index Page</h1>

<div class="table-responsive">

<table class="table table-striped table-hover">

	<tr class="small">
		<th> <%= link_to "Client", :sort => "client_id" %></th>
		<th> <%= link_to "Title", :sort => "title" %></th>
		<th> <%= link_to "Submission Date", :sort => "submission_date" %></th>
		<th> <%= link_to "Period", :sort => "period" %></th>
    <th> <%= link_to "User", :sort => "user_id" %></th>
    <th> Edit </th>
    <th> Delete </th>
	</tr>

<% @posts.each do |post| %>

	<tr class="small">
		<td> <%= post.client.try(:name) %> </td>
	
		<td> <%= post.try(:title) %> </td>
		<td> <%= post.submission_date %> </td>	
		<td> <%= post.period %> </td>	
  <td> <%= post.user.email %></td>
  <td>
      <%= link_to "Edit", edit_post_path(post), :class => 'btn btn-xs btn-success' %>
    </td>
    <td>
      <%= link_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-xs btn-warning' %>  
    </td>
  </tr>
<% end %>

<%= link_to "Create New Post", new_post_path, :class => 'btn btn-xs btn-success' %>
</table>
<%= render 'searchform' %>

</div>
</div>

</div>

app/views/posts/new.html.erb
<div class="col-md-12">
<h1 style="color:#cc3333;">Create New Post</h1>

<%= render 'form' %>

</div>
</div>

app/views/posts/show.html.erb
<div class="col-md-12">

<div class="col-md-8">


<p><h1><%=@post.client.name %></h1></p>
<p class="red"><%=@post.title%></p>
<p><%=@post.submission_date%></p>
</div>
</div>
	

app/views/posts/show_posts.html.erb
<div class="col-md-12">

<div class="col-md-8">
<div class="jumbotron">
<h1> <%= @period %> </h1>
 <% @posts.each do |post| %>
  <p><%= post.title %></p>
 <%end%>

app/views/welcome/bestpractices.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
	<div class="jumbotron">
		<h1 align="center">Best Practices</h1>
    <p align="left">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <div class="row">
  <div class="col-md-3">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua.</p>
  </div>
  <div class="col-md-3"> 
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
    aliquip ex ea commodo consequat.</p>
  </div>
  <div class="col-md-3"> 
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
    doloremque laudantium, totam rem aperiam.</p>
  </div>
  <div class="col-md-3"> 
    <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
    dicta sunt explicabo.</p>
  </div>
</div>
			<p align="left">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
      <div class="row">
  <div class="col-md-3">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua.</p>
  </div>
  <div class="col-md-3"> 
    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
    aliquip ex ea commodo consequat.</p>
  </div>
  <div class="col-md-3"> 
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
    doloremque laudantium, totam rem aperiam.</p>
  </div>
  <div class="col-md-3"> 
    <p>Eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
    dicta sunt explicabo.</p>
  </div>
</div>
			<p align="left">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</p>
	</div>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
<background class="background">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
	<div class="jumbotron">
		<h1 align="center">Welcome, ghostwriter!</h1>
			<p align="center">This portal allows you to input and keep track of your monthly writing submissions for [employername].</p>
			<p align="center">Please log in, then use the navigation bar at the top to get started.</p>
	</div>
</html>